apiVersion: skaffold/v2beta13
kind: Config
build:
  artifacts:
  - image: registry.local:5000/node-example
    context: backend
    sync:
      manual:
      # Sync all the javascript files that are in the src folder
      # with the container src folder
      - src: '*.js'
        dest: src
  local:
    useBuildkit: true

deploy:
  helm:
    releases:
    - name: test
      namespace: test
      createNamespace: true
      chartPath: ./ops/helm/test
      artifactOverrides:
        image: registry.local:5000/node-example
